#!/usr/bin/env python3
"""kaizen schemas — dataclass SSOT for kaizen's implicit JSON shapes.

Before v1.9.0, four shapes lived only in comments + scattered field
accesses across scripts. v1.19.0 extended coverage to the v1.14–v1.18
additions (workflow schemas, workflow state, knowledge index items,
brain rules, agent-formatting). Full inventory:

  v1.9.0 (initial):
    TraceEvent              — `~/.claude/.kaizen-trace/events.jsonl`
    InboxMessage            — `~/.claude/kaizen-inbox/<ts>-<n>.json`
    DaemonState             — `~/.claude/.kaizen-daemon/state.json`
    BacklogItem / Decision  — `<repo>/.workflow/backlog.json` (items[])
    BacklogStore            — `<repo>/.workflow/backlog.json` envelope

  v1.19.0 additions:
    WorkflowSchema          — `schemas/<name>/schema.yaml`
    WorkflowArtifact        —   nested item under .artifacts[]
    WorkflowApply           —   nested under .apply
    WorkflowState           — `<repo>/.workflow/state.json`
    KnowledgeItem           — `~/.claude/.kaizen-knowledge/index.db` rows
    KaizenBrainRule         — `~/.claude/brain/Notes/*.md` kaizen: block
    AgentFormattingSchema   — `skills/agent-formatting/SKILL.md` body block
    FormattingRule          —   nested under .rules[]
    ForbiddenConstruct      —   nested under .forbidden_constructs[]

Matching JSON Schemas live at `assets/schemas/*.schema.json` for
IDE / yaml-language-server / ajv consumption — generated by hand
from these dataclasses (no auto-gen yet; keep both in sync manually).

This module declares each shape as a `@dataclass`. Writers construct
typed instances and serialize via `asdict()`. Readers may use
`from_dict()` for typed access or stay dict-based (tolerant for
backward compat).

## Forward / backward compat policy

- `from_dict()` IGNORES unknown fields (forward-compat: newer writers
  can add fields that older readers don't know about).
- Missing fields fall back to the dataclass default (backward-compat:
  older writers' files load cleanly under newer readers).
- This is incremental SDD — adopt the dataclass at one writer at a
  time; on-disk shape stays compatible throughout.

## Why not Pydantic / attrs

Stdlib-only: kaizen runs in any Python 3.10+ env including
constrained CI sandboxes. `dataclasses` + `typing` + `json` cover
the use case without a pip dep.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field, fields
from typing import Any, Optional


# ─── Helpers ─────────────────────────────────────────────────────────


def from_dict(cls, data: dict):
    """Construct a dataclass instance from a dict, tolerating extra +
    missing fields. Nested dataclasses NOT auto-resolved — caller
    handles those one level at a time (kept simple to stay stdlib-only)."""
    if not isinstance(data, dict):
        raise TypeError(f"expected dict, got {type(data).__name__}")
    known = {f.name for f in fields(cls)}
    kwargs = {k: v for k, v in data.items() if k in known}
    return cls(**kwargs)


# ─── TraceEvent ──────────────────────────────────────────────────────
#
# One line in events.jsonl. Producer: trace.py event command (called
# by hooks/_trace.sh, llm_proxy.py, daemon.py, browser_mcp.py via
# PreToolUse/PostToolUse, agent dispatches).


VALID_TRACE_SOURCES = frozenset({"hook", "agent", "llm", "tool", "user", "cc", "plugin"})


@dataclass
class TraceEvent:
    ts: str                           # ISO UTC, ms precision (e.g. "2026-05-12T00:30:00.123Z")
    src: str                          # one of VALID_TRACE_SOURCES
    evt: str                          # event name (free-form within src)
    sid: str = ""                     # session_id (empty if not applicable)
    tool: str = ""                    # tool name (for src=hook|tool events)
    ms: Optional[int] = None          # duration_ms (None if not measured)
    data: dict = field(default_factory=dict)

    def to_jsonl_dict(self) -> dict:
        """Compact dict for JSONL line write — drops empty/None fields."""
        out: dict = {"ts": self.ts, "src": self.src, "evt": self.evt}
        if self.sid:
            out["sid"] = self.sid
        if self.tool:
            out["tool"] = self.tool
        if self.ms is not None:
            out["ms"] = self.ms
        if self.data:
            out["data"] = self.data
        return out

    def validate(self) -> list[str]:
        """Return list of validation errors (empty = valid)."""
        errs: list[str] = []
        if self.src not in VALID_TRACE_SOURCES:
            errs.append(f"invalid src={self.src!r} (valid: {sorted(VALID_TRACE_SOURCES)})")
        if not self.evt:
            errs.append("evt is required (non-empty)")
        if self.ms is not None and self.ms < 0:
            errs.append(f"ms must be >=0, got {self.ms}")
        return errs


# ─── InboxMessage ────────────────────────────────────────────────────
#
# One file per user prompt under ~/.claude/kaizen-inbox/<ts>-<n>.json.
# Producer: inbox.py capture (called by hooks/userprompt-inbox.sh).
# Consumer: inbox.py {list,peek,drain,stats}.


@dataclass
class InboxMessage:
    ts: str                                    # ISO UTC, ms precision
    prompt: str                                # verbatim user text
    session_id: str = ""                       # CC session uuid
    drained: bool = False                      # surfaced via PostToolUse drain?
    drained_at: Optional[str] = None           # when drained (ISO)
    drain_reason: str = ""                     # "turn-starter-completed" | ""

    def to_dict(self) -> dict:
        """Full dict for on-disk persistence (preserves nullable fields)."""
        return asdict(self)


# ─── DaemonState ─────────────────────────────────────────────────────
#
# Single file ~/.claude/.kaizen-daemon/state.json. Producer + consumer:
# daemon.py tick / status.


@dataclass
class DaemonState:
    runs: int = 0                              # incremented per tick
    last_run: Optional[str] = None             # ISO UTC
    source_hash: str = ""                      # SHA1 of plugin source dir
    cache_hash: str = ""                       # SHA1 of cached version dir
    local_sha: str = ""                        # git rev-parse HEAD (marketplace)
    remote_sha: str = ""                       # ls-remote origin master
    actions: dict = field(default_factory=dict)  # {action_name: count}

    def to_dict(self) -> dict:
        return asdict(self)


# ─── BacklogItem / BacklogDecision / BacklogStore ────────────────────
#
# .workflow/backlog.json envelope. Producer + consumer: backlog.py.
# Note: BacklogStore migration is deferred to a separate micro since
# render_md() has a stable contract that's risky to refactor in one
# step. These dataclasses are available for future adoption.


@dataclass
class BacklogItem:
    id: str                                    # "BK-NNN"
    title: str
    section: str = "next_up"                   # next_up | in_flight | done | parked
    probe: str = ""                            # grep/cargo-tree/etc. proving micro size
    verify: str = ""                           # command proving completion
    ref: str = ""                              # source quote / context
    tags: list = field(default_factory=list)
    created: Optional[str] = None              # ISO UTC
    started: Optional[str] = None
    completed: Optional[str] = None
    parked: Optional[str] = None
    parked_reason: str = ""
    committed_sha: str = ""


@dataclass
class BacklogDecision:
    text: str
    why: str = ""
    ts: Optional[str] = None


@dataclass
class BacklogStore:
    schema_version: int = 1
    kind: str = "kaizen.backlog"
    items: list = field(default_factory=list)     # list[BacklogItem]
    decisions: list = field(default_factory=list) # list[BacklogDecision]
    metadata: dict = field(default_factory=dict)  # {created, updated, ...}


# ═══ v1.19.0 additions ═══════════════════════════════════════════════


# ─── WorkflowSchema + WorkflowArtifact + WorkflowApply ───────────────
#
# `schemas/<name>/schema.yaml`. Producer: schema authors (hand-written
# yaml). Consumer: workflow_runner.py (parses to dicts; these dataclasses
# document the validated shape).


@dataclass
class WorkflowApply:
    gate: str = ""                                # artifact id that gates implementation
    progress: str = ""                            # file path that tracks progress
    description: str = ""


@dataclass
class WorkflowArtifact:
    id: str = ""                                  # kebab id, referenced by .requires[]
    generates: str = ""                           # output path or glob
    template: Optional[str] = None                # relative path; None = no template
    requires: list = field(default_factory=list)  # list[str], DAG edges
    description: str = ""
    # v1.15.0+: optional branch_* fields for Confidence-Score routing.
    # Inline list flat fields (parser-compatible without nested maps).
    branch_high: Optional[list] = None
    branch_medium: Optional[list] = None
    branch_low: Optional[list] = None


@dataclass
class WorkflowSchema:
    name: str = ""
    version: int = 1
    description: str = ""
    artifacts: list = field(default_factory=list)   # list[WorkflowArtifact]
    apply: WorkflowApply = field(default_factory=WorkflowApply)


# ─── WorkflowState ───────────────────────────────────────────────────
#
# `<repo>/.workflow/state.json`. Producer: workflow.sh (init/advance/
# branch/artifact/dispatch). Consumer: workflow.sh status + read-side
# of every other workflow command.


@dataclass
class WorkflowState:
    id: str = ""                                  # "wf-YYYYMMDD-HHMMSS"
    prompt: str = ""
    routine: str = ""                             # "audit" | "schema:<name>" | etc.
    schema_name: str = ""                         # v1.14.0+: schema-driven runs only
    stages: list = field(default_factory=list)    # list[str]
    current: int = 0
    completed: list = field(default_factory=list) # [{stage, msg, at}]
    subagent_mode: str = "no"                     # no | yes | full
    auto_mode: str = "no"                         # no | yes
    tdd_mode: str = "no"
    artifacts: dict = field(default_factory=dict) # ad-hoc {key: value}
    subagents: dict = field(default_factory=dict) # {agent_id: stage}
    branch_decisions: list = field(default_factory=list)  # v1.17.0+: [{stage, key, new_tail, at}]
    started_at: str = ""
    updated_at: str = ""


# ─── KnowledgeItem ───────────────────────────────────────────────────
#
# `~/.claude/.kaizen-knowledge/index.db` rows + the dict shape iter_*
# functions yield before insert. Producer + consumer: knowledge_index.py.


VALID_KNOWLEDGE_SOURCES = frozenset(
    {"brain-note", "plan", "backlog", "schema", "persona"}
)


@dataclass
class KnowledgeItem:
    source: str = ""                              # one of VALID_KNOWLEDGE_SOURCES
    source_path: str = ""                         # abs path, or "BK-N (path)" for backlog
    title: str = ""
    snippet: str = ""                             # first ~400 chars of body
    tags: list = field(default_factory=list)      # list[str]
    updated_at: str = ""                          # ISO or empty
    body_embedded: bool = False                   # was the snippet embedded?
    sha: str = ""                                 # 16-hex content-identity hash
    id: Optional[int] = None                      # SQLite PK, None pre-insert

    def validate(self) -> list[str]:
        errs: list[str] = []
        if self.source not in VALID_KNOWLEDGE_SOURCES:
            errs.append(
                f"invalid source={self.source!r} (valid: {sorted(VALID_KNOWLEDGE_SOURCES)})"
            )
        if not self.title:
            errs.append("title is required (non-empty)")
        return errs


# ─── KaizenBrainRule ─────────────────────────────────────────────────
#
# `~/.claude/brain/Notes/*.md` with a `kaizen:` frontmatter block.
# Producer: hand-authored brain notes. Consumer: rules.py.


VALID_BRAIN_RULE_TYPES = frozenset(
    {"deletion-allow", "check-severity", "custom-pattern", "dependency-allowlist"}
)
VALID_SEVERITY = frozenset({"skip", "warn", "block"})
VALID_PATTERN_ACTION = frozenset({"warn", "block"})


@dataclass
class KaizenBrainRule:
    name: str = ""
    description: str = ""
    source: str = ""                              # abs path to the .md
    rule_type: str = ""                           # one of VALID_BRAIN_RULE_TYPES
    # Type-specific fields (all optional; per-type validation enforces presence).
    path_glob: Optional[str] = None               # deletion-allow
    check_id: Optional[str] = None                # check-severity
    severity: Optional[str] = None                # check-severity
    pattern_regex: Optional[str] = None           # custom-pattern
    pattern_action: Optional[str] = None          # custom-pattern
    pattern_message: Optional[str] = None         # custom-pattern
    allowlist: Optional[str] = None               # dependency-allowlist (comma-sep)

    def validate(self) -> list[str]:
        errs: list[str] = []
        if self.rule_type not in VALID_BRAIN_RULE_TYPES:
            errs.append(
                f"rule_type {self.rule_type!r} not in {sorted(VALID_BRAIN_RULE_TYPES)}"
            )
            return errs
        if self.rule_type == "deletion-allow":
            if not self.path_glob:
                errs.append("deletion-allow requires path_glob")
        elif self.rule_type == "check-severity":
            if not self.check_id:
                errs.append("check-severity requires check_id")
            if self.severity not in VALID_SEVERITY:
                errs.append(
                    f"check-severity.severity must be one of {sorted(VALID_SEVERITY)}"
                )
        elif self.rule_type == "custom-pattern":
            if not self.pattern_regex:
                errs.append("custom-pattern requires pattern_regex")
            if self.pattern_action not in VALID_PATTERN_ACTION:
                errs.append(
                    f"custom-pattern.pattern_action must be one of {sorted(VALID_PATTERN_ACTION)}"
                )
        elif self.rule_type == "dependency-allowlist":
            if not self.allowlist or not [
                x.strip() for x in self.allowlist.split(",") if x.strip()
            ]:
                errs.append("dependency-allowlist requires non-empty allowlist (comma-sep)")
        return errs


# ─── AgentFormattingSchema (v1.18.0+) ────────────────────────────────
#
# Embedded yaml block in `skills/agent-formatting/SKILL.md`. Producer:
# the skill author. Consumer: future linters / gate integration / agents
# that want to verify their output compliance.


@dataclass
class FormattingRule:
    id: str = ""
    applies_to: str = ""
    pattern: Optional[str] = None
    format: dict = field(default_factory=dict)
    rationale: str = ""


@dataclass
class ForbiddenConstruct:
    description: str = ""
    example: str = ""
    fix: str = ""


@dataclass
class AgentFormattingSchema:
    schema_version: int = 1
    rules: list = field(default_factory=list)              # list[FormattingRule]
    forbidden_constructs: list = field(default_factory=list)  # list[ForbiddenConstruct]


# ─── Module self-test ────────────────────────────────────────────────


def _self_test() -> None:
    """Sanity-check round-trips. Run with: python3 schemas.py"""
    # TraceEvent
    e = TraceEvent(ts="2026-05-12T00:30:00.123Z", src="hook", evt="PreToolUse-bash",
                    tool="Bash", sid="sid-1", ms=12, data={"command": "ls"})
    assert e.validate() == []
    bad = TraceEvent(ts="x", src="bogus", evt="x")
    assert "invalid src" in bad.validate()[0]
    d = e.to_jsonl_dict()
    assert d["src"] == "hook"
    e2 = from_dict(TraceEvent, d)
    assert e2.src == "hook" and e2.tool == "Bash"

    # InboxMessage
    m = InboxMessage(ts="2026-05-12T00:31:00Z", prompt="hi", session_id="sid-1")
    md = m.to_dict()
    m2 = from_dict(InboxMessage, md)
    assert m2.prompt == "hi"

    # InboxMessage with unknown field (forward-compat)
    m3 = from_dict(InboxMessage, {**md, "future_field": "ignored"})
    assert m3.prompt == "hi"

    # DaemonState
    s = DaemonState(runs=42, actions={"refresh-cache": 3, "hygiene": 42})
    sd = s.to_dict()
    s2 = from_dict(DaemonState, sd)
    assert s2.runs == 42 and s2.actions["hygiene"] == 42

    # BacklogItem
    b = BacklogItem(id="BK-001", title="test", probe="grep ...", verify="cargo test")
    bd = asdict(b)
    b2 = from_dict(BacklogItem, bd)
    assert b2.id == "BK-001"

    # v1.19.0 additions ----

    # WorkflowSchema + WorkflowArtifact + WorkflowApply
    art = WorkflowArtifact(
        id="design",
        generates="design.md",
        requires=["analyze"],
        branch_high=["tasks", "decisions"],
        description="...",
    )
    ad = asdict(art)
    art2 = from_dict(WorkflowArtifact, ad)
    assert art2.id == "design" and art2.branch_high == ["tasks", "decisions"]

    apply_block = WorkflowApply(gate="design", progress="tasks.md")
    ws = WorkflowSchema(name="spec-driven", artifacts=[art], apply=apply_block)
    assert ws.apply.gate == "design"

    # WorkflowState
    st = WorkflowState(
        id="wf-20260512-000000",
        routine="schema:spec-driven",
        schema_name="spec-driven",
        stages=["analyze", "design", "tasks"],
        current=1,
        branch_decisions=[{"stage": "design", "key": "high", "new_tail": ["tasks"], "at": "ts"}],
    )
    sd2 = asdict(st)
    st2 = from_dict(WorkflowState, sd2)
    assert st2.schema_name == "spec-driven" and len(st2.branch_decisions) == 1

    # KnowledgeItem
    ki = KnowledgeItem(
        source="brain-note",
        source_path="/tmp/foo.md",
        title="A note",
        tags=["kaizen"],
        sha="abc123",
    )
    assert ki.validate() == []
    bad_ki = KnowledgeItem(source="bogus", title="x")
    assert "invalid source" in bad_ki.validate()[0]
    no_title = KnowledgeItem(source="brain-note", title="")
    assert "title is required" in no_title.validate()[0]

    # KaizenBrainRule — all 4 rule_types
    for r, extra in [
        (KaizenBrainRule(rule_type="deletion-allow", path_glob="tests/**"), True),
        (KaizenBrainRule(rule_type="check-severity", check_id="paired-test", severity="warn"), True),
        (KaizenBrainRule(rule_type="custom-pattern", pattern_regex="x", pattern_action="warn"), True),
        (KaizenBrainRule(rule_type="dependency-allowlist", allowlist="serde,tokio"), True),
    ]:
        assert r.validate() == [], f"unexpected errors for {r.rule_type}: {r.validate()}"
    # Negative: missing required field
    assert KaizenBrainRule(rule_type="deletion-allow").validate()  # no path_glob
    assert KaizenBrainRule(rule_type="custom-pattern", pattern_regex="x", pattern_action="bogus").validate()

    # AgentFormattingSchema + FormattingRule + ForbiddenConstruct
    fmt = AgentFormattingSchema(
        schema_version=1,
        rules=[asdict(FormattingRule(id="slash-plain", applies_to="claude-code-slash"))],
        forbidden_constructs=[
            asdict(ForbiddenConstruct(description="x", example="y", fix="z"))
        ],
    )
    fd = asdict(fmt)
    fmt2 = from_dict(AgentFormattingSchema, fd)
    assert fmt2.schema_version == 1 and len(fmt2.rules) == 1

    print("✓ all schema round-trips pass")


if __name__ == "__main__":
    _self_test()
