"""Tests for scripts/util/audit_jsonl.py — backfill .jsonl siblings
for older audit reports per pref-jsonl-indexed-deliverables.

The pain this fixes: kaizen-audit reports landed as .md before the
paired-deliverable convention existed. Older reports stayed
.md-only, so `jq` slices over historical findings weren't possible.
The regen-jsonl verb walks the audits dir + emits paired .jsonl
siblings idempotently.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

_KZ_DIR = Path(__file__).resolve().parent.parent
_SCRIPT = _KZ_DIR / "scripts/util/audit_jsonl.py"


_SAMPLE_REPORT = """\
# kaizen audit — 2026-05-17T09:36:41Z

**Scope:** (whole repo)
**Total findings:** 2

Per [link](https://example.com): boilerplate intro.

## INFO — 2

- tech-debt | 1 TODO/FIXME/XXX/HACK markers
- coverage | test-file ratio 47% (145 / 307) — healthy

---

_Generated by `/kaizen:audit`._
"""

_EMPTY_REPORT = """\
# kaizen audit — 2026-05-18T00:00:00Z

**Scope:** plugins/kaizen/
**Total findings:** 0

No findings worth surfacing this pass.

---

_Generated by `/kaizen:audit`._
"""


class _Base(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.audits = self.tmp / ".kaizen" / "workflow" / "audits"
        self.audits.mkdir(parents=True)

    def tearDown(self):
        self._tmp.cleanup()

    def _run(self, *args: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            [sys.executable, str(_SCRIPT), "--repo", str(self.tmp), *args],
            capture_output=True, text=True, timeout=15,
        )


class TestBackfill(_Base):
    def test_writes_jsonl_for_unpaired_report(self):
        md = self.audits / "2026-05-17T09-36-41Z-repo.md"
        md.write_text(_SAMPLE_REPORT, encoding="utf-8")
        r = self._run("--json")
        self.assertEqual(r.returncode, 0, r.stderr)
        out = json.loads(r.stdout)
        self.assertEqual(out["summary"]["wrote"], 1)
        jsonl = md.with_suffix(".jsonl")
        self.assertTrue(jsonl.is_file())
        rows = [json.loads(l) for l in jsonl.read_text().splitlines() if l.strip()]
        self.assertEqual(len(rows), 2)
        self.assertEqual(rows[0]["report"], "2026-05-17T09-36-41Z-repo.md")
        self.assertEqual(rows[0]["scope"], "(whole repo)")
        self.assertEqual(rows[0]["total"], 2)
        self.assertEqual(rows[0]["severity"], "INFO")
        self.assertIn("tech-debt", rows[0]["text"])

    def test_idempotent_skips_already_paired(self):
        md = self.audits / "2026-05-17T09-36-41Z-repo.md"
        md.write_text(_SAMPLE_REPORT, encoding="utf-8")
        self._run()  # first pass writes
        before = md.with_suffix(".jsonl").read_bytes()
        r = self._run("--json")
        out = json.loads(r.stdout)
        self.assertEqual(out["summary"]["paired"], 1)
        self.assertEqual(out["summary"].get("wrote", 0), 0)
        # File untouched
        after = md.with_suffix(".jsonl").read_bytes()
        self.assertEqual(before, after)

    def test_force_rewrites_existing_jsonl(self):
        md = self.audits / "x.md"
        md.write_text(_SAMPLE_REPORT, encoding="utf-8")
        self._run()
        # Stomp the jsonl with garbage; --force should restore it.
        md.with_suffix(".jsonl").write_text("garbage\n", encoding="utf-8")
        r = self._run("--force", "--json")
        out = json.loads(r.stdout)
        self.assertEqual(out["summary"]["wrote"], 1)
        rows = md.with_suffix(".jsonl").read_text().splitlines()
        self.assertEqual(len(rows), 2)

    def test_dry_run_writes_nothing(self):
        md = self.audits / "x.md"
        md.write_text(_SAMPLE_REPORT, encoding="utf-8")
        r = self._run("--dry-run", "--json")
        self.assertEqual(r.returncode, 0, r.stderr)
        out = json.loads(r.stdout)
        self.assertEqual(out["summary"]["dry-run"], 1)
        self.assertFalse(md.with_suffix(".jsonl").exists())

    def test_empty_report_skipped(self):
        md = self.audits / "empty.md"
        md.write_text(_EMPTY_REPORT, encoding="utf-8")
        r = self._run("--json")
        out = json.loads(r.stdout)
        self.assertEqual(out["summary"]["skipped"], 1)
        self.assertFalse(md.with_suffix(".jsonl").exists())

    def test_missing_audits_dir_exits_1(self):
        # Use a tmp dir that has no .kaizen/workflow/audits.
        with tempfile.TemporaryDirectory() as t:
            r = subprocess.run(
                [sys.executable, str(_SCRIPT), "--repo", t],
                capture_output=True, text=True, timeout=10,
            )
            self.assertEqual(r.returncode, 1)
            self.assertIn("no audits dir", r.stderr)


if __name__ == "__main__":
    unittest.main()
