"""kaizen auto-load — daemon-built CLAUDE.md companion.

Exploits Claude Code's `@path` import mechanism in CLAUDE.md. The
user's ~/.claude/CLAUDE.md imports this file:

    @~/.claude/.kaizen/auto-load.md

Claude Code expands the import at session start (recursive, max 5
hops), so whatever this file contains lands in context like the rest
of CLAUDE.md. The daemon rebuilds it every tick from brain Persona
top-N beliefs + active gates — no manual curation needed.

## Pure layer

- ``parse_persona(text)`` → structured ``{"directives": [...],
  "top_beliefs": [...]}``
- ``build_auto_load(persona_text, top_n, byte_budget)`` → markdown
  string (HARD-GATE wrap for must-not rules, byte-cap truncation)

## Adapter

- ``run_auto_load(state)`` — daemon job. Reads Persona, writes target.
  Env: ``KAIZEN_DAEMON_AUTO_LOAD_DISABLE``, ``KAIZEN_AUTO_LOAD_PATH``
  (default ``~/.claude/.kaizen/auto-load.md``), ``KAIZEN_BRAIN_DIR``
  (passed through to ``_brain.brain_root()``).
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(_SCRIPT_DIR))


# ─── Pure: parse + build ─────────────────────────────────────────────


_DIRECTIVE_RE = re.compile(
    r"^- \*\*(?P<text>[^*]+?)\*\*[^\[]*\[\[(?P<note>[^\]]+)\]\]",
    re.M,
)
_BELIEF_RE = re.compile(
    r"^(?P<rank>\d+)\.\s+\[\[(?P<note>[^\]]+)\]\]"
    r"(?:\s+—\s+conf=(?P<conf>[\d.]+))?"
    r"(?:\s+sources=(?P<sources>\d+))?",
    re.M,
)
_MUST_NOT_TOKENS = ("never", "must not", "no deletions", "must never",
                    "blocks", "hard-gate", "mandatory")


def _block(text: str, heading_path: str) -> str:
    """Return the body of an addressable block by heading path.

    Composes ``_brain_blocks.extract_block`` so auto_load uses the SAME
    heading addressing as ``kaizen-brain show / edit`` — one parser,
    one set of semantics, deterministic by construction.

    Returns empty string when the block isn't found (instead of None)
    so caller regexes are unaffected.
    """
    import _brain_blocks as bb
    body = bb.extract_block(text, heading_path)
    return body or ""


def parse_persona(text: str) -> dict:
    """Extract directives + top beliefs from a Persona.md body.

    Uses ``_brain_blocks.extract_block`` for section addressing
    (deterministic / reproducible / consistent with kaizen-brain show).
    Per-line patterns are regex-matched against the extracted block
    body — the inner regex is concern-specific (directive shape,
    belief metadata), but the outer block boundary is canonical.
    """
    directives = []
    for m in _DIRECTIVE_RE.finditer(_block(text, "Directives")):
        directives.append({
            "text": m.group("text").strip().rstrip("."),
            "note": m.group("note").strip(),
        })
    top_beliefs = []
    for m in _BELIEF_RE.finditer(_block(text, "Top Beliefs")):
        top_beliefs.append({
            "rank": int(m.group("rank")),
            "note": m.group("note").strip(),
            "confidence": float(m.group("conf")) if m.group("conf") else None,
            "sources": int(m.group("sources")) if m.group("sources") else None,
        })
    return {"directives": directives, "top_beliefs": top_beliefs}


def _is_hard_gate(text: str) -> bool:
    """Heuristic: rule body mentions must-not language → gate-worthy."""
    low = text.lower()
    return any(t in low for t in _MUST_NOT_TOKENS)


def _fingerprint(body: str) -> str:
    """`<!-- daemon: <ts> sha256:<hex> -->` zero-token marker.

    HTML comments are stripped from CLAUDE.md before context injection
    (per the Claude Code memory doc), so this consumes no tokens but is
    visible to the brain-drift gate when it Reads the file directly.

    Detects:
    - Hand-edits (caller's body hash != recorded sha)
    - Staleness (timestamp older than threshold)
    - Missing (file wasn't daemon-written)
    """
    import datetime as _dt
    import hashlib as _hashlib
    ts = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    sha = _hashlib.sha256(body.encode("utf-8")).hexdigest()[:12]
    return f"<!-- daemon: {ts} sha256:{sha} -->\n"


def build_auto_load(persona_text: str, *, top_n: int = 10,
                     byte_budget: int = 5000,
                     pins: list[str] | None = None) -> str:
    """Render the auto-load markdown body from Persona content.

    Top N beliefs by rank. Directives matching must-not patterns wrap
    in <HARD-GATE> blocks. ``pins`` (optional list of note refs like
    ``Notes/pref-x``) render in a dedicated ``## Pinned`` section
    above Top Beliefs — pinned notes always appear regardless of
    top_n. Pinned notes already in Top Beliefs are deduped out of
    the Pinned section (Top Beliefs ordering wins).
    """
    parsed = parse_persona(persona_text)
    parts = [
        "# kaizen auto-load",
        "",
        "> AUTO-GENERATED by `kaizen daemon` every tick. Do NOT edit by "
        "hand — your changes will be overwritten. Pin entries via "
        "`kaizen-brain pin <Note>`.",
        "",
    ]

    hard = [d for d in parsed["directives"] if _is_hard_gate(d["text"])]
    soft = [d for d in parsed["directives"] if not _is_hard_gate(d["text"])]

    if hard:
        parts.append("## Hard gates (commit-blocking)")
        parts.append("")
        parts.append("<HARD-GATE>")
        for d in hard:
            parts.append(f"- **{d['text']}** → [[{d['note']}]]")
        parts.append("</HARD-GATE>")
        parts.append("")

    if soft:
        parts.append("## Directives")
        parts.append("")
        for d in soft:
            parts.append(f"- **{d['text']}** → [[{d['note']}]]")
        parts.append("")

    beliefs = parsed["top_beliefs"][:top_n]
    # Compare without the trailing `.md` for dedup (Top Beliefs uses
    # `Notes/x.md`, pins use `Notes/x`).
    belief_keys = {b["note"].removesuffix(".md") for b in beliefs}

    pinned_unique = []
    for p in (pins or []):
        key = p.removesuffix(".md")
        if key not in belief_keys and key not in pinned_unique:
            pinned_unique.append(key)
    if pinned_unique:
        parts.append("## Pinned")
        parts.append("")
        for p in pinned_unique:
            parts.append(f"- [[{p}]]")
        parts.append("")

    if beliefs:
        parts.append("## Top beliefs")
        parts.append("")
        for b in beliefs:
            meta = []
            if b.get("confidence") is not None:
                meta.append(f"conf={b['confidence']}")
            if b.get("sources") is not None:
                meta.append(f"sources={b['sources']}")
            tail = (" — " + " ".join(meta)) if meta else ""
            parts.append(f"{b['rank']}. [[{b['note']}]]{tail}")
        parts.append("")

    rendered = "\n".join(parts)
    encoded = rendered.encode("utf-8")
    if len(encoded) > byte_budget:
        # Truncate at byte boundary, snip to nearest newline for cleanliness.
        truncated = encoded[:byte_budget].decode("utf-8", errors="ignore")
        last_nl = truncated.rfind("\n")
        if last_nl > 0:
            truncated = truncated[:last_nl]
        rendered = truncated + "\n\n> _truncated to byte_budget_\n"
    # Prepend the daemon fingerprint (HTML comment — zero token cost).
    # sha is over the rendered body so hand-edits flip the hash.
    return _fingerprint(rendered) + rendered


# ─── Adapter: daemon job ─────────────────────────────────────────────


def _default_path() -> Path:
    env = os.environ.get("KAIZEN_AUTO_LOAD_PATH")
    if env:
        return Path(env).expanduser()
    return Path.home() / ".claude" / ".kaizen" / "auto-load.md"


def _pins_path() -> Path:
    """Sandbox override: KAIZEN_AUTO_LOAD_PINS_PATH.
    Default: ~/.claude/.kaizen/auto-load-pins.json."""
    env = os.environ.get("KAIZEN_AUTO_LOAD_PINS_PATH")
    if env:
        return Path(env).expanduser()
    return Path.home() / ".claude" / ".kaizen" / "auto-load-pins.json"


def load_pins() -> list[str]:
    """Return the pinned note list (sorted, deduped). Empty when absent."""
    import json
    p = _pins_path()
    if not p.is_file():
        return []
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    if isinstance(data, list):
        return sorted(set(str(x) for x in data))
    return []


def _save_pins(pins: list[str]) -> None:
    """Atomic write of the pin list."""
    import json
    p = _pins_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(p.suffix + ".tmp")
    tmp.write_text(json.dumps(sorted(set(pins)), indent=2), encoding="utf-8")
    tmp.replace(p)


def add_pin(note: str) -> None:
    """Add ``note`` to the pin list (dedup). Note ref shape: ``Notes/<name>``."""
    pins = set(load_pins())
    pins.add(note)
    _save_pins(sorted(pins))


def remove_pin(note: str) -> None:
    """Remove ``note`` from the pin list. No-op when absent (idempotent)."""
    pins = [p for p in load_pins() if p != note]
    _save_pins(pins)


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def _gates_dir() -> Path:
    """Sandbox override: KAIZEN_GATES_DIR.
    Default: ~/.claude/.kaizen/gates/."""
    env = os.environ.get("KAIZEN_GATES_DIR")
    if env:
        return Path(env).expanduser()
    return Path.home() / ".claude" / ".kaizen" / "gates"


def _note_slug(note_ref: str) -> str:
    """Notes/pref-x → pref-x (filename without dir prefix or .md suffix)."""
    base = note_ref.rsplit("/", 1)[-1]
    return base.removesuffix(".md")


def write_cluster_gates(persona_text: str) -> list[str]:
    """Tier 3: write one gate file per hard-gate-eligible directive.

    Each file at ``<gates_dir>/<note-slug>.md`` contains a single
    `<HARD-GATE>` block with the directive + note link. User
    selectively imports the gates a project needs in its CLAUDE.md:

        @~/.claude/.kaizen/gates/pref-no-deletions.md
        @~/.claude/.kaizen/gates/pref-onion-architecture-strict.md

    Prunes files whose backing directive is no longer in Persona,
    so removing a directive from Persona auto-removes the gate file.

    Returns the list of written file paths.
    """
    parsed = parse_persona(persona_text)
    hard_directives = [d for d in parsed["directives"]
                       if _is_hard_gate(d["text"])]
    gates_dir = _gates_dir()
    gates_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    current_slugs: set[str] = set()
    for d in hard_directives:
        slug = _note_slug(d["note"])
        current_slugs.add(slug)
        path = gates_dir / f"{slug}.md"
        gate_body = (
            f"<!-- AUTO-GENERATED by kaizen daemon. Do NOT edit. "
            f"Backs directive: {slug}. -->\n"
            f"<HARD-GATE>\n"
            f"- **{d['text']}** → [[{d['note']}]]\n"
            f"</HARD-GATE>\n"
        )
        # Per-file daemon fingerprint (zero-token; brain-drift gate reads it).
        body = _fingerprint(gate_body) + gate_body
        _atomic_write(path, body)
        written.append(path)

    # Prune obsolete: any *.md file in gates_dir whose slug isn't in
    # current_slugs gets removed (directive retired from Persona).
    for p in gates_dir.glob("*.md"):
        if p.stem not in current_slugs:
            try:
                p.unlink()
            except OSError:
                pass

    return [str(p) for p in written]


_DAEMON_MARKER = "AUTO-GENERATED by kaizen daemon"


def write_project_rules(persona_text: str,
                          project_root: Path,
                          paths_glob: list[str] | None = None) -> list[str]:
    """Phase B: write per-Note hard-gate rules as native `.claude/rules/`
    files with `paths:` frontmatter.

    Each hard-gate directive in Persona becomes a single rule file at
    ``<project_root>/.claude/rules/<slug>.md`` that Claude Code's
    native path-scoping auto-loads when matching files are accessed
    (no manual @import needed; matches the canonical docs pattern).

    Args:
      persona_text: Persona.md body to parse.
      project_root: project root that hosts `.claude/rules/`.
      paths_glob:   list of glob patterns for the `paths:` frontmatter.
                    Defaults to ``["**/*"]`` (catch-all — always-on for
                    the project). Pass narrower lists like
                    ``["src/**/*.py"]`` for path-scoped activation.

    Pruning: removes existing rule files prefixed with the daemon
    AUTO-GENERATED marker comment whose slug is no longer present in
    Persona directives. Hand-authored rules (no marker) are preserved.

    Additive: complements ``write_cluster_gates`` (user-global gates
    dir). Either or both may be enabled per env (no overlap by default).

    Returns the list of written file paths.
    """
    parsed = parse_persona(persona_text)
    hard_directives = [d for d in parsed["directives"]
                       if _is_hard_gate(d["text"])]
    rules_dir = Path(project_root) / ".claude" / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)
    paths_glob = paths_glob or ["**/*"]

    # Serialize paths list as YAML inline array (KISS — no PyYAML dep)
    paths_yaml = ", ".join(f'"{p}"' for p in paths_glob)

    written: list[Path] = []
    current_slugs: set[str] = set()
    for d in hard_directives:
        slug = _note_slug(d["note"])
        current_slugs.add(slug)
        path = rules_dir / f"{slug}.md"
        # Frontmatter MUST start at line 1 (parser sees `---` only when
        # it's the file head). Fingerprint goes inline after frontmatter.
        gate_body = (
            f"<!-- {_DAEMON_MARKER}. Do NOT edit. Backs directive: {slug}. -->\n"
            f"<HARD-GATE>\n"
            f"- **{d['text']}** → [[{d['note']}]]\n"
            f"</HARD-GATE>\n"
        )
        fingerprint = _fingerprint(gate_body)
        full = (
            f"---\n"
            f"paths: [{paths_yaml}]\n"
            f"---\n"
            f"{fingerprint}"
            f"{gate_body}"
        )
        _atomic_write(path, full)
        written.append(path)

    # Prune obsolete: ONLY files we previously wrote (marker present)
    # whose slug isn't in the current set. Preserves hand-authored rules.
    for p in rules_dir.glob("*.md"):
        if p.stem in current_slugs:
            continue
        try:
            head = p.read_text(encoding="utf-8", errors="replace")[:300]
        except OSError:
            continue
        if _DAEMON_MARKER in head:
            try:
                p.unlink()
            except OSError:
                pass

    return [str(p) for p in written]


# ─── Phase M: path-scoped brain Notes → .claude/rules/ ──────────────


_FM_BLOCK_RE = re.compile(r"\A---\n(.*?)\n---\n", re.S)
_FM_LIST_INLINE_RE = re.compile(r"^paths:\s*\[(.*?)\]", re.M)
_FM_LIST_BLOCK_RE = re.compile(
    r"^paths:\s*\n((?:[ \t]+-\s*['\"]?[^\n'\"]+['\"]?\s*(?:\n|$))+)",
    re.M,
)


def _parse_note_paths(fm_text: str) -> list[str]:
    """Extract the `paths:` list from a Note's YAML frontmatter.

    Handles two YAML forms (no PyYAML dep):
    - inline: `paths: ["src/**/*.py", "tests/**/*.py"]`
    - block:  `paths:\\n  - 'src/**/*.py'\\n  - 'tests/**/*.py'`

    Returns empty list when the field is absent / malformed.
    """
    m = _FM_LIST_INLINE_RE.search(fm_text)
    if m:
        inner = m.group(1).strip()
        if not inner:
            return []
        return [s.strip().strip("'\"") for s in inner.split(",") if s.strip()]
    m = _FM_LIST_BLOCK_RE.search(fm_text)
    if m:
        out = []
        for line in m.group(1).splitlines():
            line = line.strip()
            if line.startswith("- "):
                out.append(line[2:].strip().strip("'\""))
        return out
    return []


def scan_path_scoped_notes(brain_root: Path) -> list[dict]:
    """Walk brain Notes/ and return entries with `paths:` frontmatter.

    Opt-in: only Notes that explicitly declare `paths:` are returned.
    Notes without it stay brain-only (avoid flooding project rule dirs).

    Returns: list of ``{slug, paths, text, note_path}`` where ``text``
    is the body (post-frontmatter) for inclusion in the rule.
    """
    notes_dir = Path(brain_root) / "Notes"
    if not notes_dir.is_dir():
        return []
    out: list[dict] = []
    for p in sorted(notes_dir.glob("*.md")):
        try:
            raw = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        m = _FM_BLOCK_RE.match(raw)
        if not m:
            continue
        fm_text = m.group(1)
        # Try strict-ish parse: must look well-formed (no unterminated quote)
        if fm_text.count('"') % 2 or fm_text.count("'") % 2:
            continue
        paths = _parse_note_paths(fm_text)
        if not paths:
            continue
        body = raw[m.end():].lstrip("\n")
        out.append({
            "slug":      p.stem,
            "paths":     paths,
            "text":      body,
            "note_path": str(p),
        })
    return out


def write_note_rules(brain_root: Path, project_root: Path) -> list[str]:
    """Emit path-scoped brain Notes as ``<project>/.claude/rules/note-<slug>.md``.

    Each rule includes the Note's body + a `paths:` frontmatter copied
    from the Note's own frontmatter. The ``note-`` filename prefix
    namespaces these against directive gates (which use plain
    `<slug>.md`).

    Prunes obsolete: removes daemon-authored `note-*.md` rules whose
    backing Note no longer declares `paths:`. Hand-authored
    `note-*.md` files (no marker) are preserved.

    Returns the list of written file paths.
    """
    notes = scan_path_scoped_notes(Path(brain_root))
    rules_dir = Path(project_root) / ".claude" / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    current_slugs: set[str] = set()
    for note in notes:
        slug = note["slug"]
        current_slugs.add(slug)
        path = rules_dir / f"note-{slug}.md"
        paths_yaml = ", ".join(f'"{p}"' for p in note["paths"])
        rule_body = (
            f"<!-- {_DAEMON_MARKER}. Do NOT edit. "
            f"Backs brain Note: {slug}. -->\n"
            f"{note['text']}"
        )
        fingerprint = _fingerprint(rule_body)
        full = (
            f"---\n"
            f"paths: [{paths_yaml}]\n"
            f"---\n"
            f"{fingerprint}"
            f"{rule_body}"
        )
        _atomic_write(path, full)
        written.append(path)

    for p in rules_dir.glob("note-*.md"):
        if p.stem.removeprefix("note-") in current_slugs:
            continue
        try:
            head = p.read_text(encoding="utf-8", errors="replace")[:300]
        except OSError:
            continue
        if _DAEMON_MARKER in head:
            try:
                p.unlink()
            except OSError:
                pass

    return [str(p) for p in written]


# ─── Phase F: cross-tool rule compat ────────────────────────────────


# Map of external rule file → slug used in the emitted rule filename.
# AGENTS.md is the cross-agent convention (Cursor / Aider / Windsurf
# upstream); .cursorrules + .windsurfrules are tool-specific files
# many repos already ship.
_EXTERNAL_RULE_FILES: list[tuple[str, str]] = [
    ("AGENTS.md",       "external-agents.md"),
    (".cursorrules",    "external-cursorrules.md"),
    (".windsurfrules",  "external-windsurfrules.md"),
]


def write_external_rule_imports(project_root: Path) -> list[str]:
    """Phase F: emit `.claude/rules/external-<name>.md` for each
    detected cross-tool rule file in ``project_root``.

    Each emitted rule:
    - Has `paths: ["**/*"]` frontmatter (always-load for the project)
    - Body contains `@<external-file>` so Claude Code's @import
      mechanism pulls the external content into context — no
      duplication, no manual sync.

    Pruning: removes `external-*.md` rule files whose backing external
    file no longer exists, but only if the rule carries the daemon
    marker (hand-authored `external-*.md` preserved).

    Idempotent re-run produces byte-identical output (fingerprint
    stable for stable content).

    Returns the list of written rule file paths.
    """
    project_root = Path(project_root)
    rules_dir = project_root / ".claude" / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    current_slugs: set[str] = set()
    for ext_name, rule_basename in _EXTERNAL_RULE_FILES:
        ext_path = project_root / ext_name
        if not ext_path.is_file():
            continue
        rule_slug = rule_basename.removesuffix(".md")
        current_slugs.add(rule_slug)
        rule_path = rules_dir / rule_basename
        rule_body = (
            f"<!-- {_DAEMON_MARKER}. Do NOT edit. "
            f"Backs external rule file: {ext_name}. -->\n"
            f"<!-- The @import below pulls the external file's content "
            f"into context. Edit the external file directly. -->\n"
            f"@{ext_name}\n"
        )
        fingerprint = _fingerprint(rule_body)
        full = (
            f"---\n"
            f'paths: ["**/*"]\n'
            f"---\n"
            f"{fingerprint}"
            f"{rule_body}"
        )
        _atomic_write(rule_path, full)
        written.append(rule_path)

    # Prune daemon-authored external-*.md rules whose external file
    # no longer exists. Hand-authored ones (no marker) are preserved.
    for p in rules_dir.glob("external-*.md"):
        if p.stem in current_slugs:
            continue
        try:
            head = p.read_text(encoding="utf-8", errors="replace")[:300]
        except OSError:
            continue
        if _DAEMON_MARKER in head:
            try:
                p.unlink()
            except OSError:
                pass

    return [str(p) for p in written]


def run_auto_load(state: dict) -> tuple[bool, str, str]:
    """Daemon job: read Persona, build + atomically write auto-load.md.

    Honors KAIZEN_DAEMON_AUTO_LOAD_DISABLE. Returns the standard
    (ok, msg, action_key) tuple consumed by daemon.py::tick().
    """
    action = "auto-load"
    if os.environ.get("KAIZEN_DAEMON_AUTO_LOAD_DISABLE") == "1":
        return True, "disabled via env", action
    try:
        import _brain
        persona = _brain.brain_root() / "Persona.md"
        if not persona.is_file():
            return True, "no Persona.md (brain not seeded)", action
        text = persona.read_text(encoding="utf-8")
        body = build_auto_load(text, pins=load_pins())
        _atomic_write(_default_path(), body)
        cluster_files = write_cluster_gates(text)
        return True, (f"wrote {len(body)}B + {len(cluster_files)} cluster "
                       "gate(s)"), action
    except OSError as e:
        return False, f"OSError: {e}", action


# ─── CLI (for ad-hoc / debug invocation) ──────────────────────────────


def main(argv: list[str] | None = None) -> int:
    import argparse
    p = argparse.ArgumentParser(prog="kaizen-auto-load",
                                 description="Render auto-load.md from Persona.")
    p.add_argument("--persona", help="Persona.md path (default: brain root)")
    p.add_argument("--out", help="output path (default: ~/.claude/.kaizen/auto-load.md)")
    p.add_argument("--top-n", type=int, default=10)
    p.add_argument("--budget", type=int, default=5000)
    p.add_argument("--print", action="store_true",
                   help="print to stdout instead of writing")
    args = p.parse_args(argv)

    if args.persona:
        persona = Path(args.persona)
    else:
        import _brain
        persona = _brain.brain_root() / "Persona.md"
    if not persona.is_file():
        print(f"auto-load: Persona not found at {persona}", file=sys.stderr)
        return 2
    text = persona.read_text(encoding="utf-8")
    body = build_auto_load(text, top_n=args.top_n, byte_budget=args.budget)
    if args.print:
        print(body)
    else:
        out = Path(args.out) if args.out else _default_path()
        _atomic_write(out, body)
        cluster_files = write_cluster_gates(text)
        print(f"auto-load: wrote {len(body)}B → {out} "
              f"(+ {len(cluster_files)} cluster gate(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
