"""kaizen auto-load — daemon-built CLAUDE.md companion.

Exploits Claude Code's `@path` import mechanism in CLAUDE.md. The
user's ~/.claude/CLAUDE.md imports this file:

    @~/.claude/.kaizen/auto-load.md

Claude Code expands the import at session start (recursive, max 5
hops), so whatever this file contains lands in context like the rest
of CLAUDE.md. The daemon rebuilds it every tick from brain Persona
top-N beliefs + active gates — no manual curation needed.

## Pure layer

- ``parse_persona(text)`` → structured ``{"directives": [...],
  "top_beliefs": [...]}``
- ``build_auto_load(persona_text, top_n, byte_budget)`` → markdown
  string (HARD-GATE wrap for must-not rules, byte-cap truncation)

## Adapter

- ``run_auto_load(state)`` — daemon job. Reads Persona, writes target.
  Env: ``KAIZEN_DAEMON_AUTO_LOAD_DISABLE``, ``KAIZEN_AUTO_LOAD_PATH``
  (default ``~/.claude/.kaizen/auto-load.md``), ``KAIZEN_BRAIN_DIR``
  (passed through to ``_brain.brain_root()``).
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(_SCRIPT_DIR))


# ─── Pure: parse + build ─────────────────────────────────────────────


_DIRECTIVE_RE = re.compile(
    r"^- \*\*(?P<text>[^*]+?)\*\*[^\[]*\[\[(?P<note>[^\]]+)\]\]",
    re.M,
)
_BELIEF_RE = re.compile(
    r"^(?P<rank>\d+)\.\s+\[\[(?P<note>[^\]]+)\]\]"
    r"(?:\s+—\s+conf=(?P<conf>[\d.]+))?"
    r"(?:\s+sources=(?P<sources>\d+))?",
    re.M,
)
_MUST_NOT_TOKENS = ("never", "must not", "no deletions", "must never",
                    "blocks", "hard-gate", "mandatory")


def _block(text: str, heading_path: str) -> str:
    """Return the body of an addressable block by heading path.

    Composes ``_brain_blocks.extract_block`` so auto_load uses the SAME
    heading addressing as ``kaizen-brain show / edit`` — one parser,
    one set of semantics, deterministic by construction.

    Returns empty string when the block isn't found (instead of None)
    so caller regexes are unaffected.
    """
    import _brain_blocks as bb
    body = bb.extract_block(text, heading_path)
    return body or ""


def parse_persona(text: str) -> dict:
    """Extract directives + top beliefs from a Persona.md body.

    Uses ``_brain_blocks.extract_block`` for section addressing
    (deterministic / reproducible / consistent with kaizen-brain show).
    Per-line patterns are regex-matched against the extracted block
    body — the inner regex is concern-specific (directive shape,
    belief metadata), but the outer block boundary is canonical.
    """
    directives = []
    for m in _DIRECTIVE_RE.finditer(_block(text, "Directives")):
        directives.append({
            "text": m.group("text").strip().rstrip("."),
            "note": m.group("note").strip(),
        })
    top_beliefs = []
    for m in _BELIEF_RE.finditer(_block(text, "Top Beliefs")):
        top_beliefs.append({
            "rank": int(m.group("rank")),
            "note": m.group("note").strip(),
            "confidence": float(m.group("conf")) if m.group("conf") else None,
            "sources": int(m.group("sources")) if m.group("sources") else None,
        })
    return {"directives": directives, "top_beliefs": top_beliefs}


def _is_hard_gate(text: str) -> bool:
    """Heuristic: rule body mentions must-not language → gate-worthy."""
    low = text.lower()
    return any(t in low for t in _MUST_NOT_TOKENS)


def build_auto_load(persona_text: str, *, top_n: int = 10,
                     byte_budget: int = 5000,
                     pins: list[str] | None = None) -> str:
    """Render the auto-load markdown body from Persona content.

    Top N beliefs by rank. Directives matching must-not patterns wrap
    in <HARD-GATE> blocks. ``pins`` (optional list of note refs like
    ``Notes/pref-x``) render in a dedicated ``## Pinned`` section
    above Top Beliefs — pinned notes always appear regardless of
    top_n. Pinned notes already in Top Beliefs are deduped out of
    the Pinned section (Top Beliefs ordering wins).
    """
    parsed = parse_persona(persona_text)
    parts = [
        "# kaizen auto-load",
        "",
        "> AUTO-GENERATED by `kaizen daemon` every tick. Do NOT edit by "
        "hand — your changes will be overwritten. Pin entries via "
        "`kaizen-brain pin <Note>`.",
        "",
    ]

    hard = [d for d in parsed["directives"] if _is_hard_gate(d["text"])]
    soft = [d for d in parsed["directives"] if not _is_hard_gate(d["text"])]

    if hard:
        parts.append("## Hard gates (commit-blocking)")
        parts.append("")
        parts.append("<HARD-GATE>")
        for d in hard:
            parts.append(f"- **{d['text']}** → [[{d['note']}]]")
        parts.append("</HARD-GATE>")
        parts.append("")

    if soft:
        parts.append("## Directives")
        parts.append("")
        for d in soft:
            parts.append(f"- **{d['text']}** → [[{d['note']}]]")
        parts.append("")

    beliefs = parsed["top_beliefs"][:top_n]
    # Compare without the trailing `.md` for dedup (Top Beliefs uses
    # `Notes/x.md`, pins use `Notes/x`).
    belief_keys = {b["note"].removesuffix(".md") for b in beliefs}

    pinned_unique = []
    for p in (pins or []):
        key = p.removesuffix(".md")
        if key not in belief_keys and key not in pinned_unique:
            pinned_unique.append(key)
    if pinned_unique:
        parts.append("## Pinned")
        parts.append("")
        for p in pinned_unique:
            parts.append(f"- [[{p}]]")
        parts.append("")

    if beliefs:
        parts.append("## Top beliefs")
        parts.append("")
        for b in beliefs:
            meta = []
            if b.get("confidence") is not None:
                meta.append(f"conf={b['confidence']}")
            if b.get("sources") is not None:
                meta.append(f"sources={b['sources']}")
            tail = (" — " + " ".join(meta)) if meta else ""
            parts.append(f"{b['rank']}. [[{b['note']}]]{tail}")
        parts.append("")

    rendered = "\n".join(parts)
    encoded = rendered.encode("utf-8")
    if len(encoded) > byte_budget:
        # Truncate at byte boundary, snip to nearest newline for cleanliness.
        truncated = encoded[:byte_budget].decode("utf-8", errors="ignore")
        last_nl = truncated.rfind("\n")
        if last_nl > 0:
            truncated = truncated[:last_nl]
        rendered = truncated + "\n\n> _truncated to byte_budget_\n"
    return rendered


# ─── Adapter: daemon job ─────────────────────────────────────────────


def _default_path() -> Path:
    env = os.environ.get("KAIZEN_AUTO_LOAD_PATH")
    if env:
        return Path(env).expanduser()
    return Path.home() / ".claude" / ".kaizen" / "auto-load.md"


def _pins_path() -> Path:
    """Sandbox override: KAIZEN_AUTO_LOAD_PINS_PATH.
    Default: ~/.claude/.kaizen/auto-load-pins.json."""
    env = os.environ.get("KAIZEN_AUTO_LOAD_PINS_PATH")
    if env:
        return Path(env).expanduser()
    return Path.home() / ".claude" / ".kaizen" / "auto-load-pins.json"


def load_pins() -> list[str]:
    """Return the pinned note list (sorted, deduped). Empty when absent."""
    import json
    p = _pins_path()
    if not p.is_file():
        return []
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    if isinstance(data, list):
        return sorted(set(str(x) for x in data))
    return []


def _save_pins(pins: list[str]) -> None:
    """Atomic write of the pin list."""
    import json
    p = _pins_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(p.suffix + ".tmp")
    tmp.write_text(json.dumps(sorted(set(pins)), indent=2), encoding="utf-8")
    tmp.replace(p)


def add_pin(note: str) -> None:
    """Add ``note`` to the pin list (dedup). Note ref shape: ``Notes/<name>``."""
    pins = set(load_pins())
    pins.add(note)
    _save_pins(sorted(pins))


def remove_pin(note: str) -> None:
    """Remove ``note`` from the pin list. No-op when absent (idempotent)."""
    pins = [p for p in load_pins() if p != note]
    _save_pins(pins)


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def run_auto_load(state: dict) -> tuple[bool, str, str]:
    """Daemon job: read Persona, build + atomically write auto-load.md.

    Honors KAIZEN_DAEMON_AUTO_LOAD_DISABLE. Returns the standard
    (ok, msg, action_key) tuple consumed by daemon.py::tick().
    """
    action = "auto-load"
    if os.environ.get("KAIZEN_DAEMON_AUTO_LOAD_DISABLE") == "1":
        return True, "disabled via env", action
    try:
        import _brain
        persona = _brain.brain_root() / "Persona.md"
        if not persona.is_file():
            return True, "no Persona.md (brain not seeded)", action
        text = persona.read_text(encoding="utf-8")
        body = build_auto_load(text, pins=load_pins())
        _atomic_write(_default_path(), body)
        return True, f"wrote {len(body)}B", action
    except OSError as e:
        return False, f"OSError: {e}", action


# ─── CLI (for ad-hoc / debug invocation) ──────────────────────────────


def main(argv: list[str] | None = None) -> int:
    import argparse
    p = argparse.ArgumentParser(prog="kaizen-auto-load",
                                 description="Render auto-load.md from Persona.")
    p.add_argument("--persona", help="Persona.md path (default: brain root)")
    p.add_argument("--out", help="output path (default: ~/.claude/.kaizen/auto-load.md)")
    p.add_argument("--top-n", type=int, default=10)
    p.add_argument("--budget", type=int, default=5000)
    p.add_argument("--print", action="store_true",
                   help="print to stdout instead of writing")
    args = p.parse_args(argv)

    if args.persona:
        persona = Path(args.persona)
    else:
        import _brain
        persona = _brain.brain_root() / "Persona.md"
    if not persona.is_file():
        print(f"auto-load: Persona not found at {persona}", file=sys.stderr)
        return 2
    text = persona.read_text(encoding="utf-8")
    body = build_auto_load(text, top_n=args.top_n, byte_budget=args.budget)
    if args.print:
        print(body)
    else:
        out = Path(args.out) if args.out else _default_path()
        _atomic_write(out, body)
        print(f"auto-load: wrote {len(body)}B → {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
