"""kaizen-shim — make the `shim-and-sweep` routine actionable.

The shim-and-sweep routine (schemas/shim-and-sweep/schema.yaml) is the
generalized form of shodan's borg-loop discipline: every relocation
during a large refactor leaves a 1-line re-export shim at the old
path; shims accumulate in a deletion manifest; one user-gated commit
sweeps them all at the end.

This CLI converts the discipline from "three-step manual procedure
per shim" into a single command that:
  - copies content to the canonical (new) location
  - writes a per-language shim at the old location
  - appends the old path to the deletion manifest

A separate `sweep` subcommand runs the final user-gated deletion in
one revertible commit (preceded by a safety tag).

## Subcommands

    kaizen-shim init <slug>
        Create `.kaizen/workflow/deletion-manifest-<slug>.txt`.

    kaizen-shim carve <old> <new> --slug <s> [--reexport <module>]
        Copy <old> → <new>, replace <old> with a shim, append manifest.

    kaizen-shim list --slug <s> [--include-keep]
        Print manifest entries.

    kaizen-shim sweep --slug <s> [--allow-delete] [--dry-run]
        F-FINAL — `git rm` every non-KEEP manifest entry in one
        commit (preceded by `git tag pre-sweep-<slug>`). Requires
        `KAIZEN_ALLOW_DELETE=1` or `--allow-delete`.

## Shim shapes per language

    .rs           pub use <reexport>::*;
    .py           from <reexport> import *
    .ts, .tsx,    export * from "<relative_new_path>";
    .js, .mjs

For Rust + Python, `--reexport` is REQUIRED (we can't infer the
module path from file location alone). For TS/JS, the shim is a
filesystem-relative path computed automatically.

## Manifest format

Plain text at `.kaizen/workflow/deletion-manifest-<slug>.txt`:

    # Deletion manifest — <slug>
    # generated by kaizen-shim. one entry per line.
    #
    2026-05-13 path/to/old/file.rs
    2026-05-13 path/to/old/dir/mod.rs  KEEP — back-compat surface

KEEP entries survive the sweep; everything else is retired.

See `skills/shim-and-sweep/SKILL.md` for the full routine.
"""
from __future__ import annotations

import argparse
import datetime as dt
import os
import shutil
import subprocess
import sys
from pathlib import Path

# ─── Manifest helpers ────────────────────────────────────────────────

def manifest_path(slug: str, root: Path | None = None) -> Path:
    """Resolve <repo>/.kaizen/workflow/deletion-manifest-<slug>.txt."""
    root = root or _repo_root()
    return root / ".kaizen" / "workflow" / f"deletion-manifest-{slug}.txt"

def _repo_root(start: Path | None = None) -> Path:
    """Walk up to find the git root (or the closest .kaizen/ dir)."""
    cur = (start or Path.cwd()).resolve()
    for p in (cur, *cur.parents):
        if (p / ".git").exists() or (p / ".kaizen").is_dir():
            return p
    # Fall back to cwd — caller can recover.
    return cur

def manifest_init(slug: str, root: Path | None = None) -> Path:
    """Create the manifest file with a header. Idempotent."""
    p = manifest_path(slug, root)
    if p.exists():
        return p
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        f"# Deletion manifest — {slug}\n"
        "# generated by kaizen-shim. one entry per line.\n"
        "# Format: YYYY-MM-DD <path>  [KEEP <reason>]\n"
        "#\n",
        encoding="utf-8",
    )
    return p

def manifest_append(slug: str, rel_path: str, root: Path | None = None, *, keep: str | None = None) -> None:
    """Append an entry to the manifest. Creates manifest if absent."""
    p = manifest_init(slug, root)
    line = f"{dt.date.today().isoformat()} {rel_path}"
    if keep:
        line += f"  KEEP — {keep}"
    with p.open("a", encoding="utf-8") as fh:
        fh.write(line + "\n")

def manifest_read(slug: str, root: Path | None = None) -> list[tuple[str, str, str | None]]:
    """Parse manifest → list of (date, path, keep_reason_or_None)."""
    p = manifest_path(slug, root)
    if not p.is_file():
        return []
    out: list[tuple[str, str, str | None]] = []
    for raw in p.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        # YYYY-MM-DD <path> [KEEP <reason>]
        date, _, rest = line.partition(" ")
        if "KEEP" in rest:
            path_part, _, keep_part = rest.partition("KEEP")
            keep_reason = keep_part.strip(" —-").strip() or "back-compat"
            out.append((date, path_part.strip(), keep_reason))
        else:
            out.append((date, rest.strip(), None))
    return out

# ─── Per-language shim writers ───────────────────────────────────────

def _ts_relative_path(old: Path, new: Path) -> str:
    """Compute a TS-style import path: relative from old's dir to new (without ext).

    Pure-string computation — does not touch the filesystem or
    `os.getcwd()`, so it's safe to call from tests that have removed
    their cwd."""
    old_parts = list(old.parent.parts)
    new_parts = list(new.with_suffix("").parts)
    i = 0
    while i < min(len(old_parts), len(new_parts)) and old_parts[i] == new_parts[i]:
        i += 1
    ups = [".."] * (len(old_parts) - i)
    down = list(new_parts[i:])
    rel = "/".join(ups + down) if (ups or down) else "."
    if not rel.startswith(".") and not rel.startswith("/"):
        rel = "./" + rel
    return rel

def shim_contents(old: Path, new: Path, reexport: str | None) -> str:
    """Return the file contents that should replace <old> after carving to <new>."""
    suffix = old.suffix.lower()
    if suffix == ".rs":
        if not reexport:
            raise ValueError(
                f"--reexport is required for Rust shims "
                f"(canonical module path, e.g. 'shodan_nodes::runtime::borg::state'); "
                f"got None for {old}"
            )
        return (
            f"// kaizen-shim: this file is a re-export of {reexport}.\n"
            f"// Original content lives at {new}. Scheduled for sweep removal.\n"
            f"pub use {reexport}::*;\n"
        )
    if suffix == ".py":
        if not reexport:
            raise ValueError(
                f"--reexport is required for Python shims "
                f"(dotted module path, e.g. 'mypkg.nodes.borg.state'); "
                f"got None for {old}"
            )
        return (
            f"\"\"\"kaizen-shim: re-export of {reexport}.\n\n"
            f"Original content lives at {new}. Scheduled for sweep removal.\n"
            f"\"\"\"\n"
            f"from {reexport} import *  # noqa: F401,F403\n"
        )
    if suffix in (".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"):
        rel = _ts_relative_path(old, new)
        return (
            f"// kaizen-shim: re-export of {new}.\n"
            f"// Original content lives there. Scheduled for sweep removal.\n"
            f"export * from \"{rel}\";\n"
        )
    raise ValueError(
        f"unsupported shim language for {old} (extension {suffix!r}); "
        "supported: .rs .py .ts .tsx .js .jsx .mjs .cjs"
    )

# ─── Carve operation ─────────────────────────────────────────────────

def carve(
    old: Path,
    new: Path,
    slug: str,
    *,
    reexport: str | None = None,
    root: Path | None = None,
    dry_run: bool = False,
) -> dict:
    """Copy <old> → <new>, replace <old> with a shim, append manifest.

    Returns a dict describing the actions taken. Raises ValueError on
    bad inputs; caller handles user-facing error formatting.
    """
    root = root or _repo_root()
    old = old.resolve() if old.is_absolute() else (root / old).resolve()
    new = new.resolve() if new.is_absolute() else (root / new).resolve()

    if not old.is_file():
        raise ValueError(f"source not found: {old}")
    if old == new:
        raise ValueError(f"<old> and <new> must differ (got {old})")

    # Generate shim FIRST so a bad --reexport fails before we move anything.
    shim_body = shim_contents(old, new, reexport)

    actions: dict = {
        "from": str(old.relative_to(root)) if old.is_relative_to(root) else str(old),
        "to": str(new.relative_to(root)) if new.is_relative_to(root) else str(new),
        "language": old.suffix.lower(),
        "shim_first_line": shim_body.splitlines()[2] if old.suffix == ".rs"
                           else shim_body.splitlines()[-1],
    }

    if dry_run:
        actions["dry_run"] = True
        return actions

    if not new.exists():
        new.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(old, new)
        actions["copied"] = True
    else:
        # Target already exists — common when carving is partially done
        # already. We don't overwrite; we just install the shim.
        actions["copied"] = False
        actions["note"] = "target already exists; not overwriting"

    old.write_text(shim_body, encoding="utf-8")
    actions["shim_written"] = True

    manifest_append(slug, str(old.relative_to(root)), root=root)
    actions["manifest_appended"] = True
    actions["manifest"] = str(manifest_path(slug, root).relative_to(root))

    return actions

# ─── Sweep operation ─────────────────────────────────────────────────

def _run_git(args: list[str], root: Path, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "-C", str(root), *args], check=check, capture_output=True, text=True)

def sweep(
    slug: str,
    *,
    root: Path | None = None,
    allow_delete: bool = False,
    dry_run: bool = False,
) -> dict:
    """F-FINAL — `git rm` non-KEEP manifest entries in one revertible commit.

    Refuses to run unless `allow_delete=True` OR `KAIZEN_ALLOW_DELETE=1`
    is set. Tags `pre-sweep-<slug>` before deleting so rollback is
    `git reset --hard pre-sweep-<slug>`.
    """
    root = root or _repo_root()
    if not allow_delete and os.environ.get("KAIZEN_ALLOW_DELETE") != "1":
        raise PermissionError(
            "sweep refused: requires --allow-delete or KAIZEN_ALLOW_DELETE=1 "
            "(F-FINAL is user-gated by design — see "
            "skills/shim-and-sweep/SKILL.md Iron Law 4)"
        )

    entries = manifest_read(slug, root)
    to_delete = [p for _, p, keep in entries if keep is None]
    keep = [(p, k) for _, p, k in entries if k is not None]

    if not to_delete:
        return {"deleted": [], "kept": keep, "tag": None, "note": "manifest empty after KEEP filter"}

    result: dict = {
        "deleted": to_delete,
        "kept": keep,
        "tag": f"pre-sweep-{slug}",
        "dry_run": dry_run,
    }

    if dry_run:
        return result

    # Safety tag
    _run_git(["tag", "-f", f"pre-sweep-{slug}"], root, check=False)
    # Stage deletions
    for p in to_delete:
        _run_git(["rm", "--", p], root, check=False)
    return result

# ─── CLI ─────────────────────────────────────────────────────────────

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="kaizen-shim",
        description="Operate on a shim-and-sweep refactor (init / carve / list / sweep).",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    p_init = sub.add_parser("init", help="Create a deletion manifest for a new refactor.")
    p_init.add_argument("slug", help="Short identifier (used in filename + safety tag)")

    p_carve = sub.add_parser(
        "carve",
        help="Copy <old> → <new>, replace <old> with a re-export shim, append manifest.",
    )
    p_carve.add_argument("old", help="Source path that will become a shim.")
    p_carve.add_argument("new", help="Canonical (target) path where content lives.")
    p_carve.add_argument("--slug", required=True, help="Refactor slug.")
    p_carve.add_argument(
        "--reexport",
        help="Canonical module path (Rust crate::module, Python pkg.module). Required for .rs/.py.",
    )
    p_carve.add_argument("--dry-run", action="store_true", help="Print the plan; do not write.")

    p_list = sub.add_parser("list", help="Print the deletion manifest.")
    p_list.add_argument("--slug", required=True)
    p_list.add_argument(
        "--include-keep",
        action="store_true",
        help="Include KEEP entries in the listing (default: show all).",
    )

    p_sweep = sub.add_parser(
        "sweep",
        help="F-FINAL: `git rm` non-KEEP manifest entries in one revertible commit.",
    )
    p_sweep.add_argument("--slug", required=True)
    p_sweep.add_argument(
        "--allow-delete",
        action="store_true",
        help="Authorize the sweep (overrides KAIZEN_ALLOW_DELETE env).",
    )
    p_sweep.add_argument("--dry-run", action="store_true")

    return p

def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    root = _repo_root()

    try:
        if args.cmd == "init":
            p = manifest_init(args.slug, root)
            print(f"kaizen-shim init: created {p.relative_to(root)}")
            return 0

        if args.cmd == "carve":
            result = carve(
                Path(args.old),
                Path(args.new),
                args.slug,
                reexport=args.reexport,
                root=root,
                dry_run=args.dry_run,
            )
            for k, v in result.items():
                print(f"  {k}: {v}")
            return 0

        if args.cmd == "list":
            entries = manifest_read(args.slug, root)
            for date, path, keep in entries:
                if keep:
                    print(f"  {date}  {path}  KEEP — {keep}")
                else:
                    print(f"  {date}  {path}")
            print(f"  ─── {len(entries)} entries ───")
            return 0

        if args.cmd == "sweep":
            result = sweep(
                args.slug,
                root=root,
                allow_delete=args.allow_delete,
                dry_run=args.dry_run,
            )
            for k, v in result.items():
                if isinstance(v, list) and len(v) > 6:
                    print(f"  {k}: {len(v)} items ({v[:3]} …)")
                else:
                    print(f"  {k}: {v}")
            if not args.dry_run and result.get("deleted"):
                deleted_count = len(result["deleted"])
                print()
                print("  Next: review with `git diff --cached`, then commit, e.g.:")
                print("    KAIZEN_ALLOW_DELETE=1 git commit -m \\")
                print(f"      '{args.slug}-SWEEP: retire {deleted_count} shim(s)'")
            return 0

    except PermissionError as e:
        sys.stderr.write(f"kaizen-shim: {e}\n")
        return 2
    except ValueError as e:
        sys.stderr.write(f"kaizen-shim: {e}\n")
        return 1

    return 0

if __name__ == "__main__":
    sys.exit(main())
